# Mouse on
set -g mouse on

# Ctrl + A for prefix
set-option -g prefix C-b

# Index of windows starts from 1
set -g base-index 1
setw -g pane-base-index 1

# New keybindings
unbind c
bind -r t new-window
bind -r C-t new-window -c "#{pane_current_path}"

unbind k
bind -r w kill-pane
bind -r C-w kill-window


