# set shell
set -g default-shell /bin/zsh

# Mouse on
set -g mouse on

# Ctrl + A for prefix
set-option -g prefix C-a

# Index of windows starts from 1
set -g base-index 1
setw -g pane-base-index 1

# New keybindings
unbind c
bind -r t new-window
bind -r C-t new-window -c "#{pane_current_path}"

unbind k
bind -r w kill-pane
bind -r W kill-window

setw -g mode-keys vi

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

bind > swap-pane -D
bind < swap-pane -U

unbind n
unbind p
bind -r K previous-window 
bind -r J next-window

bind _ split-window -v
bind - split-window -h

# Status bar
set-option -g status on
set -g status-interval 1
set -g status-justify left

setw -g monitor-activity on
set -g visual-activity on

set-option -g status-bg colour236
set-option -g status-fg white

