local appmenu = {}

appmenu.Accessories = {
    { 'Ark', 'ark', '/usr/share/icons/hicolor/128x128/apps/ark.png' },
    { 'BalenaEtcher', '"/usr/bin/balena-etcher-electron"', '/usr/share/icons/hicolor/128x128/apps/balena-etcher-electron.png' },
    { 'Character Map', 'gucharmap' },
    { 'Filelight', 'filelight', '/usr/share/icons/hicolor/128x128/apps/filelight.png' },
    { 'HP Device Manager', 'hp-toolbox', '/usr/share/hplip/data/images/128x128/hp_logo.png' },
    { 'Jupyter Qt console', 'jupyter qtconsole', '/usr/lib/python3.10/site-packages/qtconsole/resources/icon/JupyterConsole.svg' },
    { 'KBackup', 'kbackup', '/usr/share/icons/hicolor/16x16/apps/kbackup.png' },
    { 'KCalc', 'kcalc' },
    { 'KCharSelect', 'kcharselect --qwindowtitle "KCharSelect"' },
    { 'KFloppy', 'kfloppy -qwindowtitle "KFloppy"', '/usr/share/icons/hicolor/128x128/apps/kfloppy.png' },
    { 'KGpg', 'kgpg', '/usr/share/icons/hicolor/128x128/apps/kgpg.png' },
    { 'KMail Import Wizard', 'akonadiimportwizard', '/usr/share/icons/hicolor/128x128/apps/kontact-import-wizard.png' },
    { 'KTeaTime', 'kteatime', '/usr/share/icons/hicolor/16x16/apps/kteatime.png' },
    { 'KTimer', 'ktimer', '/usr/share/icons/hicolor/128x128/apps/ktimer.png' },
    { 'KWrite', 'kwrite', '/usr/share/icons/hicolor/128x128/apps/kwrite.png' },
    { 'Kate', 'kate -b', '/usr/share/icons/hicolor/128x128/apps/kate.png' },
    { 'Klipper', 'klipper' },
    { 'Kvantum Manager', 'kvantummanager', '/usr/share/icons/hicolor/scalable/apps/kvantum.svg' },
    { 'Neovim', 'xterm -e nvim', '/usr/share/icons/hicolor/128x128/apps/nvim.png' },
    { 'PCManFM-Qt File Manager', 'pcmanfm-qt' },
    { 'Qalculate! (Qt)', 'qalculate-qt', '/usr/share/icons/hicolor/128x128/apps/qalculate-qt.png' },
    { 'Software Token', 'stoken-gui' },
    { 'Software Token (small)', 'stoken-gui --small' },
    { 'Spectacle', '/usr/bin/spectacle', '/usr/share/icons/hicolor/16x16/apps/spectacle.png' },
    { 'SpeedCrunch', 'speedcrunch' },
    { 'Sweeper', 'sweeper' },
    { 'Touché', 'com.github.joseexposito.touche', '/usr/share/icons/hicolor/128x128/apps/com.github.joseexposito.touche.svg' },
    { 'Vifm', 'xterm -e vifm' },
    { 'Vim', 'xterm -e vim', '/usr/share/icons/hicolor/48x48/apps/gvim.png' },
    { 'compton', 'compton', '/usr/share/icons/hicolor/48x48/apps/compton.png' },
    { 'ipython', 'xterm -e ipython' },
    { 'nitrogen', 'nitrogen', '/usr/share/icons/hicolor/128x128/apps/nitrogen.png' },
    { 'picom', 'picom' },
}

appmenu.Development = {
    { 'CMake', 'cmake-gui', '/usr/share/icons/hicolor/128x128/apps/CMakeSetup.png' },
    { 'Cuttlefish', 'cuttlefish' },
    { 'Electron', 'electron' },
    { 'Icon Browser', 'yad-icon-browser', '/usr/share/icons/hicolor/128x128/apps/yad.png' },
    { 'Jupyter Qt console', 'jupyter qtconsole', '/usr/lib/python3.10/site-packages/qtconsole/resources/icon/JupyterConsole.svg' },
    { 'KDiff3', 'kdiff3', '/usr/share/icons/hicolor/128x128/apps/kdiff3.png' },
    { 'Plasma Engine Explorer', 'plasmaengineexplorer' },
    { 'Plasma Global Theme Explorer', 'lookandfeelexplorer' },
    { 'Plasma Theme Explorer', 'plasmathemeexplorer' },
    { 'Qt Assistant', 'assistant', '/usr/share/icons/hicolor/128x128/apps/assistant.png' },
    { 'Qt Designer', 'designer', '/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png' },
    { 'Qt Linguist', 'linguist', '/usr/share/icons/hicolor/128x128/apps/linguist.png' },
    { 'Qt QDBusViewer', 'qdbusviewer', '/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png' },
    { 'UserFeedback Console', 'UserFeedbackConsole' },
    { 'ipython', 'xterm -e ipython' },
}

appmenu.Education = {
    { 'LibreOffice Math', 'libreoffice --math', '/usr/share/icons/hicolor/128x128/apps/libreoffice-math.png' },
    { 'Minuet', 'minuet', '/usr/share/icons/hicolor/128x128/apps/minuet.png' },
}

appmenu.Games = {
    { 'EpicGamesLauncher', 'env "/home/ledity/PortWINE/PortProton/data/scripts/start.sh" "/home/ledity/PortWINE/PortProton/data/pfx/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe"', '/home/ledity/PortWINE/PortProton/data/img/EpicGamesLauncher.png' },
    { 'GZDoom', 'gzdoom', '/usr/share/icons/hicolor/256x256/apps/gzdoom.xpm' },
    { 'Knights', 'knights --icon /usr/share/icons/hicolor/16x16/apps/knights.png -qwindowtitle "Knights"', '/usr/share/icons/hicolor/16x16/apps/knights.png' },
    { 'PortProton', 'env /home/ledity/PortWINE/PortProton/data/scripts/start.sh', '/home/ledity/PortWINE/PortProton/data/img/w.png' },
    { 'Steam (Runtime)', '/usr/bin/steam-runtime', '/usr/share/icons/hicolor/16x16/apps/steam.png' },
    { 'xsnow', 'xsnow' },
}

appmenu.Graphics = {
    { 'Flameshot', '/usr/bin/flameshot', '/usr/share/icons/hicolor/128x128/apps/org.flameshot.Flameshot.png' },
    { 'GNU Image Manipulation Program', 'gimp-2.10', '/usr/share/icons/hicolor/16x16/apps/gimp.png' },
    { 'Gwenview', 'gwenview', '/usr/share/icons/hicolor/128x128/apps/gwenview.png' },
    { 'Inkscape', 'inkscape', '/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png' },
    { 'KRuler', 'kruler', '/usr/share/icons/hicolor/128x128/apps/kruler.png' },
    { 'KolourPaint', 'kolourpaint', '/usr/share/icons/hicolor/128x128/apps/kolourpaint.png' },
    { 'Krita', 'krita', '/usr/share/icons/hicolor/128x128/apps/krita.png' },
    { 'LXImage', 'lximage-qt', '/usr/share/icons/hicolor/48x48/apps/lximage-qt.png' },
    { 'LibreOffice Draw', 'libreoffice --draw', '/usr/share/icons/hicolor/128x128/apps/libreoffice-draw.png' },
    { 'Okular', 'okular', '/usr/share/icons/hicolor/128x128/apps/okular.png' },
    { 'Screenshot', 'lximage-qt --screenshot' },
    { 'XSane - Scanning', 'xsane' },
    { 'digiKam', 'digikam -qwindowtitle "digiKam"', '/usr/share/icons/hicolor/128x128/apps/digikam.png' },
    { 'showFoto', 'showfoto -qwindowtitle "showFoto"', '/usr/share/icons/hicolor/128x128/apps/showfoto.png' },
}

appmenu.Internet = {
    { 'Avahi SSH Server Browser', '/usr/bin/bssh' },
    { 'Avahi VNC Server Browser', '/usr/bin/bvnc' },
    { 'Chromium', '/usr/bin/chromium', '/usr/share/icons/hicolor/128x128/apps/chromium.png' },
    { 'Discord', '/usr/bin/discord' },
    { 'Firefox', '/usr/lib/firefox/firefox', '/usr/share/icons/hicolor/128x128/apps/firefox.png' },
    { 'KDE Connect', 'kdeconnect-app', '/usr/share/icons/hicolor/scalable/apps/kdeconnect.svg' },
    { 'KDE Connect Indicator', 'kdeconnect-indicator', '/usr/share/icons/hicolor/scalable/apps/kdeconnect.svg' },
    { 'KDE Connect SMS', 'kdeconnect-sms', '/usr/share/icons/hicolor/scalable/apps/kdeconnect.svg' },
    { 'KMail', 'kmail -qwindowtitle "KMail"', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'KMail Refresh Settings', 'kmail-refresh-settings -qwindowtitle "KMail Refresh Settings"', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'KTnef', 'ktnef', '/usr/share/icons/hicolor/48x48/apps/ktnef.png' },
    { 'MBoxImporter', 'mboximporter', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'Open on connected device via KDE Connect', 'kdeconnect-handler --open', '/usr/share/icons/hicolor/scalable/apps/kdeconnect.svg' },
    { 'PIM Data Exporter', 'pimdataexporter' },
    { 'Sieve Editor', 'sieveeditor', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'Steam (Runtime)', '/usr/bin/steam-runtime', '/usr/share/icons/hicolor/16x16/apps/steam.png' },
    { 'Telegram Desktop', 'telegram-desktop -quit', '/usr/share/icons/hicolor/128x128/apps/telegram.png' },
    { 'Tok', 'org.kde.Tok', '/usr/share/icons/hicolor/scalable/apps/org.kde.Tok.svg' },
    { 'Zoom', '/usr/bin/zoom' },
    { 'qBittorrent', 'qbittorrent', '/usr/share/icons/hicolor/128x128/apps/qbittorrent.png' },
    { 'qutebrowser', 'qutebrowser --untrusted-args', '/usr/share/icons/hicolor/128x128/apps/qutebrowser.png' },
}

appmenu.Office = {
    { 'KMail', 'kmail -qwindowtitle "KMail"', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'KMail Refresh Settings', 'kmail-refresh-settings -qwindowtitle "KMail Refresh Settings"', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'KTnef', 'ktnef', '/usr/share/icons/hicolor/48x48/apps/ktnef.png' },
    { 'LibreOffice', 'libreoffice', '/usr/share/icons/hicolor/128x128/apps/libreoffice-startcenter.png' },
    { 'LibreOffice Base', 'libreoffice --base', '/usr/share/icons/hicolor/128x128/apps/libreoffice-base.png' },
    { 'LibreOffice Calc', 'libreoffice --calc', '/usr/share/icons/hicolor/128x128/apps/libreoffice-calc.png' },
    { 'LibreOffice Draw', 'libreoffice --draw', '/usr/share/icons/hicolor/128x128/apps/libreoffice-draw.png' },
    { 'LibreOffice Impress', 'libreoffice --impress', '/usr/share/icons/hicolor/128x128/apps/libreoffice-impress.png' },
    { 'LibreOffice Math', 'libreoffice --math', '/usr/share/icons/hicolor/128x128/apps/libreoffice-math.png' },
    { 'LibreOffice Writer', 'libreoffice --writer', '/usr/share/icons/hicolor/128x128/apps/libreoffice-writer.png' },
    { 'MBoxImporter', 'mboximporter', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'ONLYOFFICE Desktop Editors', '/usr/bin/onlyoffice-desktopeditors', '/usr/share/icons/hicolor/128x128/apps/onlyoffice-desktopeditors.png' },
    { 'Okular', 'okular', '/usr/share/icons/hicolor/128x128/apps/okular.png' },
    { 'Sieve Editor', 'sieveeditor', '/usr/share/icons/hicolor/128x128/apps/kmail.png' },
    { 'qpdfview', 'qpdfview --unique', '/usr/share/icons/hicolor/scalable/apps/qpdfview.svg' },
}

appmenu.MultiMedia = {
    { 'Audacity', 'env UBUNTU_MENUPROXY=0 audacity', '/usr/share/icons/hicolor/16x16/apps/audacity.png' },
    { 'Dragon Player', 'dragon', '/usr/share/icons/hicolor/128x128/apps/dragonplayer.png' },
    { 'Echomixer', 'echomixer', '/usr/share/icons/hicolor/48x48/apps/echomixer.png' },
    { 'Elisa', 'elisa', '/usr/share/icons/hicolor/128x128/apps/elisa.png' },
    { 'Envy24 Control', 'envy24control', '/usr/share/icons/hicolor/48x48/apps/envy24control.png' },
    { 'HDAJackRetask', 'hdajackretask' },
    { 'HDSPConf', 'hdspconf', '/usr/share/icons/hicolor/48x48/apps/hdspconf.png' },
    { 'HDSPMixer', 'hdspmixer', '/usr/share/icons/hicolor/48x48/apps/hdspmixer.png' },
    { 'Hwmixvolume', 'hwmixvolume', '/usr/share/icons/hicolor/128x128/apps/hwmixvolume.png' },
    { 'Kdenlive', 'kdenlive', '/usr/share/icons/hicolor/128x128/apps/kdenlive.png' },
    { 'Kid3', 'kid3', '/usr/share/icons/hicolor/128x128/apps/kid3.png' },
    { 'OBS Studio', 'obs', '/usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png' },
    { 'PulseAudio Volume Control', 'pavucontrol-qt' },
    { 'Qt V4L2 test Utility', 'qv4l2', '/usr/share/icons/hicolor/16x16/apps/qv4l2.png' },
    { 'Qt V4L2 video capture utility', 'qvidcap', '/usr/share/icons/hicolor/16x16/apps/qvidcap.png' },
    { 'QtAV Player', 'Player -f', '/usr/share/icons/hicolor/scalable/apps/QtAV.svg' },
    { 'QtAV QML Player', 'QMLPlayer -f', '/usr/share/icons/hicolor/scalable/apps/QtAV.svg' },
    { 'SimpleScreenRecorder', 'simplescreenrecorder --logfile', '/usr/share/icons/hicolor/128x128/apps/simplescreenrecorder.png' },
    { 'Tenacity', 'env UBUNTU_MENUPROXY=0 tenacity', '/usr/share/icons/hicolor/16x16/apps/tenacity.png' },
    { 'VLC media player', '/usr/bin/vlc --started-from-file', '/usr/share/icons/hicolor/128x128/apps/vlc.png' },
    { 'Virtual MIDI Piano Keyboard', '/home/ledity/Applications/vmpk/vmpk-0.8.4-linux-x86_64.AppImage', '/home/ledity/Applications/vmpk/vmpk_128x128.png' },
    { 'mpv Media Player', 'mpv --player-operation-mode=pseudo-gui --', '/usr/share/icons/hicolor/128x128/apps/mpv.png' },
}

appmenu.Settings = {
    { 'Advanced Network Configuration', 'nm-connection-editor' },
    { 'Bluetooth Manager', 'blueman-manager', '/usr/share/icons/hicolor/128x128/apps/blueman.png' },
    { 'Customize Look and Feel', 'lxappearance' },
    { 'Desktop', 'pcmanfm-qt --desktop-pref=general' },
    { 'Fingerprint GUI', 'fingerprint-gui --debug', '/usr/share/icons/hicolor/16x16/apps/fingerprint-gui.png' },
    { 'Grub Customizer', 'grub-customizer', '/usr/share/icons/hicolor/128x128/apps/grub-customizer.svg' },
    { 'IBus Preferences', 'ibus-setup', '/usr/share/icons/hicolor/scalable/apps/ibus-setup.svg' },
    { 'KDE Connect Settings', 'kdeconnect-settings', '/usr/share/icons/hicolor/scalable/apps/kdeconnect.svg' },
    { 'KDE System Settings', 'systemsettings5' },
    { 'Kvantum Manager', 'kvantummanager', '/usr/share/icons/hicolor/scalable/apps/kvantum.svg' },
    { 'Print Settings', 'system-config-printer' },
    { 'PulseAudio Preferences', 'paprefs' },
    { 'Qt5 Settings', 'qt5ct' },
    { 'Qt6 Settings', 'qt6ct' },
    { 'Screensaver', 'xscreensaver-settings' },
    { 'YAD settings', 'yad-settings', '/usr/share/icons/hicolor/128x128/apps/yad.png' },
}

appmenu.System = {
    { 'Avahi Zeroconf Browser', '/usr/bin/avahi-discover' },
    { 'Discover', 'plasma-discover', '/usr/share/icons/hicolor/128x128/apps/plasmadiscover.png' },
    { 'Dolphin', 'dolphin' },
    { 'Grub Customizer', 'grub-customizer', '/usr/share/icons/hicolor/128x128/apps/grub-customizer.svg' },
    { 'Hardware Locality lstopo', 'lstopo' },
    { 'Htop', 'xterm -e htop', '/usr/share/icons/hicolor/scalable/apps/htop.svg' },
    { 'KDE Partition Manager', 'partitionmanager', '/usr/share/icons/hicolor/scalable/apps/partitionmanager.svg' },
    { 'KDiskFree', 'kdf -qwindowtitle "KDiskFree"', '/usr/share/icons/hicolor/128x128/apps/kdf.png' },
    { 'KSystemLog', 'ksystemlog -qwindowtitle "KSystemLog"' },
    { 'KWalletManager', 'kwalletmanager5', '/usr/share/icons/hicolor/128x128/apps/kwalletmanager.png' },
    { 'Konsole', 'konsole' },
    { 'KwikDisk', 'kwikdisk -qwindowtitle "KwikDisk"', '/usr/share/icons/hicolor/128x128/apps/kwikdisk.png' },
    { 'Manage Printing', '/usr/bin/xdg-open http://localhost:631/', '/usr/share/icons/hicolor/128x128/apps/cups.png' },
    { 'Alacritty', 'alacritty' },
    { 'Octopi', '/usr/bin/octopi' },
    { 'Octopi CacheCleaner', '/usr/bin/octopi-cachecleaner' },
    { 'Oracle VM VirtualBox', 'VirtualBox', '/usr/share/icons/hicolor/128x128/mimetypes/virtualbox.png' },
    { 'Print Settings', 'system-config-printer' },
    { 'QTerminal', 'qterminal --drop' },
    { 'QTerminal drop down', 'qterminal --drop' },
    { 'System Monitor', 'plasma-systemmonitor' },
    { 'UXTerm', 'uxterm' },
    { 'Vifm', 'xterm -e vifm' },
    { 'XTerm', 'xterm' },
    { 'Yakuake', 'yakuake', '/usr/share/icons/hicolor/128x128/apps/yakuake.png' },
    { 'dconf Editor', 'dconf-editor', '/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png' },
    { 'ranger', 'xterm -e ranger' },
}

appmenu.Miscellaneous = {
    { 'CMus', 'xterm -e cmus' },
    { 'MatLab', '/usr/local/MATLAB/R2021a/bin/matlab' },
    { 'Plasma Windowed', 'plasmawindowed' },
    { 'hp-uiscan', '/usr/bin/hp-uiscan', '/usr/share/icons/Humanity/devices/48/printer.svg' },
}

appmenu.Appmenu = {
    { 'Accessories', appmenu.Accessories },
    { 'Development', appmenu.Development },
    { 'Education', appmenu.Education },
    { 'Games', appmenu.Games },
    { 'Graphics', appmenu.Graphics },
    { 'Internet', appmenu.Internet },
    { 'Office', appmenu.Office },
    { 'MultiMedia', appmenu.MultiMedia },
    { 'Settings', appmenu.Settings },
    { 'System', appmenu.System },
    { 'Miscellaneous', appmenu.Miscellaneous },
}

return appmenu