#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down
echo "down the last running theme"


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backend &> /dev/null & 
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi
echo "boot picom or compton if it exists"

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
echo "set the theme.toml config"


#set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore
elif [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi


#xbindkeys
if [ -x "$(command -v xbindkeys)" ]; then
  xbindkeys -p &
fi


#touchpad settings
if [ -x "$(command -v xinput)" ]; then
  if xinput list-props "ELAN2602:00 04F3:3109 Touchpad" | grep 299; then
    xinput set-prop "ELAN2602:00 04F3:3109 Touchpad" 299 1 &
  fi
  if xinput list-props "ELAN2602:00 04F3:3109 Touchpad" | grep 308; then
    xinput set-prop "ELAN2602:00 04F3:3109 Touchpad" 308 0.00003 &
  fi
fi


index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=index+1
done

#monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
#leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | read -r width x y
#barname="bottom0"
#monitor=$monitor offsetx=$x y=$y width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
