modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["web", "term", "other", "docs", "music", "video", "games", "vbox"]
layouts = ["MainAndVertStack", "LeftWiderRightStack", "EvenHorizontal", "CenterMain", "CenterMainBalanced", "Monocle"]
scratchpad = []
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

[[keybind]]
command = "HardReload"
modifier = ["modkey", "Shift", "Control"]
key = "r"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "FloatingToTile"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "SetLayout"
value = "MainAndVertStack"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "SetLayout"
value = "LeftWiderRightStack"
modifier = ["modkey", "Shift"]
key = "a"

[[keybind]]
command = "SetLayout"
value = "EvenHorizontal"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey", "Shift"]
key = "s"

[[keybind]]
command = "SetLayout"
value = "CenterMainBalanced"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "SetLayout"
value = "CenterMain"
modifier = ["modkey", "Shift"]
key = "d"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "RotateTag"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "i"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "u"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "Execute"
value = "rofi -show run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey", "Shift"]
key = "b"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 0' && firefox"
modifier = ["modkey"]
key = "b"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 1' && alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "pcmanfm-qt"
modifier = ["modkey", "Shift"]
key = "f"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 2' && pcmanfm-qt"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "qalculate-qt"
modifier = ["modkey", "Shift"]
key = "c"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 2' && qalculate-qt"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "Execute"
value = "libreoffice"
modifier = ["modkey", "Shift"]
key = "o"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 3' && libreoffice"
modifier = ["modkey"]
key = "o"

[[keybind]]
command = "Execute"
value = "alacritty -e cmus"
modifier = ["modkey", "Shift"]
key = "m"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 4' && alacritty -e cmus"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "vlc"
modifier = ["modkey", "Shift"]
key = "v"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 5' && vlc"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 6' && steam"
modifier = ["modkey"]
key = "g"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 7' && virtualbox"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "Execute"
value = "leftwm-command 'SendWorkspaceToTag 0 7' && firefox --new-window ~/ArchWiki"
modifier = ["modkey"]
key = "z"

